### ISSUE TITLE
Partial match/annotation

### ISSUE THREAD

**Issue by rojinsafavi** [jason-weirather/AlignQC#10]
Hi Jason,
Sorry to bother you again!
I was wondering if you can clarify what exactly partial annotation and partial match are? in the manuscript it says:

"A read is assigned to a reference transcript if it can cover the first and last exons with any length, and the internal exons with   80% length. When multiple exons are present and both the read and the reference transcript have the same consecutive exons, the match is called as a “full-length” match, otherwise, it is referred to as a “partial” match."

Thanks!
Rojin

**Comment by jason-weirather** [comment]
Hi Rojin,

No problem at all sorry for not catching your last question in time.  I'll try to answer it here.  If you have the file where the reads have all been assigned a name of a transcript, you could use that get transcript level counts, but PLEASE note that AlignQC wasn't purpose-built for annotating and hasn't been tested or compared against other tools for this purpose.  You can get per transcript counts by taking counts of each reads transcript name.  If you want to have a bit more certainty that you have properly assigned transcript names, but lose some of your reads you can stick to the ones marked as full match. (although then you will not have single exon genes included and you need to pick them up separately).  Getting to your question about the partial annotation and match.

partial annotation / partial match is the same thing.  It means that a read share at least 1 exon, but if there are more exons shared then its more likely that you are getting the correct transcript called.  The ones that are called full-length match mean that for multi exon reads you are matching every exon of a multi exon gene (at least 1 base on the first and last exon, and 80 mutual overlap of any central exons).  

So if I was using this to call transcripts, I would probably only look at the ones described as full-length match.  Unless the original gene is a singe exon gene, then I'd take the partial matched reads matching to those.  

I hope that helps. Let me know if theres anything I could describe better or should draw up.

Thanks,

Jason

**Comment by rojinsafavi** [comment]
Thanks Jason,
Just to clarify that and make sure that I'm understanding it right:


In case that a read is multi exon, and it aligns perfectly in full length to some where in genome, and as partially to somewhere else in the genome, it will only be assigned to the full length region is that correct?
And in  **Distribution of identified reference transcripts** and **Distribution of annotated reads 
 graphs**, the full length reads are not included in partial read bar is that correct? so that I can be sure that the ones that are gray are always partial reads.
If an annotated transcript only has one exon, this read will always be considered as a partial read? even in the graphs( meaning that it will be gray all the time).
In the same graphs, if a read is partially aligned I guess based on the bottom graph I can say how many exons of that partially annotated read were detected, is that correct? and I assume that the order is kept, but it is possible that for example only 2nd and 4rth exons are detected.

Thanks Jason!
Best,
Rojin

**Comment by jason-weirather** [comment]
1. Correct, each read is assigned to one and only one transcript, and prioritized by its best full length match, and highest percent partial match after that.
2. No, for the partial read graph, it includes either full or partial.  
3. Yes, single exon reads/genes only get classified as partial matches regardless of how they match.
4. Regarding the definition of partial, for the portion of the read that partially matches a transcript, yes, the order must be correct, and the information about these matches I think is kept in the read annotation file.  If only the 2nd and 4th exons are dectected, this read would still be assigned as a partial match, but only according to the best match of either the 2nd or the 4th exon.  its not sophisticated enough to do any maximum likelihood calculation based on all the information if it doesn't fit the expected exon order.

**Comment by rojinsafavi** [comment]
Thanks Jason :)

**Comment by rojinsafavi** [comment]
Sorry Jason, I have one more question regarding "**Distribution of annotated reads**" graph. From the graph title I assumed that the graph corresponds to all annotated reads. But when I look at the graph I see the peach color which represents unannotated reads. My assumption is that this peach color corresponds to reads that were aligned to somewhere in the genome, but had no annotation. Is that the correct assumption? 
Thanks :)

**Comment by rojinsafavi** [comment]
Hi Jason, sorry to bother you again! I was wondering if you can provide some clarification on the question I asked whenever you get a chance :)
Thank you very much!
Rojin
