### ISSUE TITLE
Illumina alignment

### ISSUE THREAD

**Issue by abayega** [jason-weirather/AlignQC#5]
Hi,

I am aligning >750 million 100bp illumina reads to a reference genome on a system with 128Gb memory and 48 cores. I have assigned 40 threads but alignqc seems to fail to go even past the first index stage. Is this too much data for alignqc or is there something i am doing wrong?

Thanks

**Comment by jason-weirather** [comment]
Hi Abayega, I understand the problem and sorry for the inconvenience, but AlignQC was made more for the purpose of analyzing third generation sequencing with much lower read counts < 1 million reads.  If you switch to the development branch of AlignQC (dev) there have been some performance improvements.  A version update will be out soon.  If you are interested in the error pattern evaluation, I recommend downsampling your data. I've used AlignQC with illumina data, but only on downsampled sets.

**Comment by abayega** [comment]
Ah, thanks for the advice. I will try the dev version as I wait for the update. Thanks once again
